/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InternalErrorIndexRouteImport } from './routes/internal-error/index'
import { Route as VerificationPasswordIndexRouteImport } from './routes/verification/password/index'
import { Route as VerificationOtpIndexRouteImport } from './routes/verification/otp/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalErrorIndexRoute = InternalErrorIndexRouteImport.update({
  id: '/internal-error/',
  path: '/internal-error/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationPasswordIndexRoute =
  VerificationPasswordIndexRouteImport.update({
    id: '/verification/password/',
    path: '/verification/password/',
    getParentRoute: () => rootRouteImport,
  } as any)
const VerificationOtpIndexRoute = VerificationOtpIndexRouteImport.update({
  id: '/verification/otp/',
  path: '/verification/otp/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/internal-error': typeof InternalErrorIndexRoute
  '/verification/otp': typeof VerificationOtpIndexRoute
  '/verification/password': typeof VerificationPasswordIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/internal-error': typeof InternalErrorIndexRoute
  '/verification/otp': typeof VerificationOtpIndexRoute
  '/verification/password': typeof VerificationPasswordIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/internal-error/': typeof InternalErrorIndexRoute
  '/verification/otp/': typeof VerificationOtpIndexRoute
  '/verification/password/': typeof VerificationPasswordIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/internal-error'
    | '/verification/otp'
    | '/verification/password'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/internal-error' | '/verification/otp' | '/verification/password'
  id:
    | '__root__'
    | '/'
    | '/internal-error/'
    | '/verification/otp/'
    | '/verification/password/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InternalErrorIndexRoute: typeof InternalErrorIndexRoute
  VerificationOtpIndexRoute: typeof VerificationOtpIndexRoute
  VerificationPasswordIndexRoute: typeof VerificationPasswordIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal-error/': {
      id: '/internal-error/'
      path: '/internal-error'
      fullPath: '/internal-error'
      preLoaderRoute: typeof InternalErrorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification/password/': {
      id: '/verification/password/'
      path: '/verification/password'
      fullPath: '/verification/password'
      preLoaderRoute: typeof VerificationPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification/otp/': {
      id: '/verification/otp/'
      path: '/verification/otp'
      fullPath: '/verification/otp'
      preLoaderRoute: typeof VerificationOtpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InternalErrorIndexRoute: InternalErrorIndexRoute,
  VerificationOtpIndexRoute: VerificationOtpIndexRoute,
  VerificationPasswordIndexRoute: VerificationPasswordIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
